./main_queryset_estimates --sds OpenStreetMap --ds india --regp > ~/india/regp.csv
./main_queryset_estimates --sds OpenStreetMap --ds india --eqd > ~/india/eqd.csv
./main_queryset_estimates --sds OpenStreetMap --ds india --qts > ~/india/qts.csv
./main_queryset_estimates --sds OpenStreetMap --ds india --gxt > ~/india/gxt.csv
./main_queryset_estimates --sds OpenStreetMap --ds india --est-area > ~/india/est-area.csv
./main_queryset_estimates --sds OpenStreetMap --ds india --sampling > ~/india/sampling.csv
./main_queryset_estimates --sds OpenStreetMap --ds india --xgb > ~/india/xgb.csv
./main_queryset_estimates --sds OpenStreetMap --ds india --eboxgb > ~/india/eboxgb.csv
./main_queryset_estimates --sds OpenStreetMap --ds india --exgb > ~/india/exgb.csv
./main_queryset_estimates --sds OpenStreetMap --ds us-south --regp > ~/us-south/regp.csv
./main_queryset_estimates --sds OpenStreetMap --ds us-south --eqd > ~/us-south/eqd.csv
./main_queryset_estimates --sds OpenStreetMap --ds us-south --qts > ~/us-south/qts.csv
./main_queryset_estimates --sds OpenStreetMap --ds us-south --gxt > ~/us-south/gxt.csv
./main_queryset_estimates --sds OpenStreetMap --ds us-south --est-area > ~/us-south/est-area.csv
./main_queryset_estimates --sds OpenStreetMap --ds us-south --sampling > ~/us-south/sampling.csv
./main_queryset_estimates --sds OpenStreetMap --ds us-south --xgb > ~/us-south/xgb.csv
./main_queryset_estimates --sds OpenStreetMap --ds us-south --eboxgb > ~/us-south/eboxgb.csv
./main_queryset_estimates --sds OpenStreetMap --ds us-south --exgb > ~/us-south/exgb.csv
./main_queryset_estimates --sds OpenStreetMap --ds netherlands --regp > ~/netherlands/regp.csv
./main_queryset_estimates --sds OpenStreetMap --ds netherlands --eqd > ~/netherlands/eqd.csv
./main_queryset_estimates --sds OpenStreetMap --ds netherlands --qts > ~/netherlands/qts.csv
./main_queryset_estimates --sds OpenStreetMap --ds netherlands --gxt > ~/netherlands/gxt.csv
./main_queryset_estimates --sds OpenStreetMap --ds netherlands --est-area > ~/netherlands/est-area.csv
./main_queryset_estimates --sds OpenStreetMap --ds netherlands --sampling > ~/netherlands/sampling.csv
./main_queryset_estimates --sds OpenStreetMap --ds netherlands --xgb > ~/netherlands/xgb.csv
./main_queryset_estimates --sds OpenStreetMap --ds netherlands --eboxgb > ~/netherlands/eboxgb.csv
./main_queryset_estimates --sds OpenStreetMap --ds netherlands --exgb > ~/netherlands/exgb.csv
